enhancement(core/tasks): consolidate build/force code
denis-ev/VivumLab pull request #16
Opened 2020-09-24 13:04 UTC by voryzen

consolidates the build and force code for the build task.

2020-09-24 23:16 UTC, denis-ev requested changes
@voryzen There are some open conflicts now, after merging the other PRs.

2020-09-25 00:54 UTC, voryzen commented
I'll have some time this afternoon

2020-09-25 00:56 UTC, voryzen commented
I'll have some time this afternoon

2020-09-25 03:49 UTC, merged

2020-10-07 01:50 UTC, denis-ev commented
:tada: This PR is included in version 0.1.0 :tada:

The release is available on:
- `v0.1.0`
- [GitHub release](https://github.com/VivumLab/VivumLab/releases/tag/v0.1.0)
- `v0.1.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2020-10-07 02:43 UTC, denis-ev commented
:tada: This PR is included in version 0.1.0 :tada:

The release is available on:
- `v0.1.0`
- [GitHub release](https://github.com/VivumLab/VivumLab/releases/tag/v0.1.0)
- `v0.1.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2020-10-07 03:06 UTC, denis-ev commented
:tada: This PR is included in version 0.1.0 :tada:

The release is available on:
- `v0.1.0`
- [GitHub release](https://github.com/VivumLab/VivumLab/releases/tag/v0.1.0)
- `v0.1.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: